version: '3.9'
services:
  app:
    container_name: go-concurrency-server
    environment:
      - PORT=${PORT}
      - ENV=${ENV}
      - EXPONEA_URL=${EXPONEA_URL}
    tty: true
    image: concurrency-server:go
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - .:/app
